### ISSUE TITLE
Error when opening a book in koreader

### ISSUE THREAD

**Issue by EastEriq** [ckilb/pocketbooksync.koplugin#1]
I get a dialog with this message
`Error detected at Getting pocketbook book settings record.Error is Error: unrecognized token ""1447"`
_twice_ each time when opening the first two books from the main pocketbook screen.
I have opened other books without getting this message, will see if that was a transient glitch.
It is unclear to me upon which conditions the pocketbook librarian is really giving some visual percentage progress hint on books opened with KR, and upon which conditions (cold reboot perhaps?) the info is updated, but I have already reported that in the mobileread threads.

**Comment by EastEriq** [comment]
PB631, 5.20.1527. Quite possible that the database tables have been slightly changed in 6.x

**Comment by EastEriq** [comment]
KoReader 2023050100000. Trying the next one soon

**Comment by EastEriq** [comment]
```
/var/tmp # cat currentPageUpdateLog.txt 
Starting page update Wed Jul 19 22:35:39 IDT 2023
SELECT ID FROM BOOK ORDER BY LAST_OPEN DESC LIMIT 1;
KoReader book id: 173
SELECT TOTAL_PAGES FROM PAGE_STAT_DATA WHERE ID_BOOK=173 ORDER BY START_TIME DESC LIMIT 1;
KoReader Total Page Count: 1348
KoReader Current Page Number 755
SELECT TITLE FROM BOOK WHERE ID_BOOK="173";
KoReader Current Book Title Petrolio
SELECT ID FROM BOOKS_IMPL WHERE TRIM(UPPER(TITLE))=TRIM(UPPER(Petrolio));
PocketBook ID: 1447
1446
Error: unrecognized token: ""1447"
```

**Comment by EastEriq** [comment]
I suspect the problem is getting more than a single `PocketBook ID:`. Possibly because the book was downloaded twice/moved around/don't remember, and produced more than a single entry in the database. I think I have observed something the like, already

**Comment by ckilb** [comment]
Hello @EastEriq  the visual percentage should be updated immediately using this plugin... So you open a book in KOReader, change a few pages, click the home button. Pocketbook will refresh the screen and show the updated info.

Just to double-check, the script you've posted here works on your device, right?
https://www.mobileread.com/forums/showpost.php?p=4328117&postcount=18

Looks like the generated SQL is invalid in your case. Which is weird because 1) it works for me and 2) if something is wrong witht the syntax being used, it should already break at some earlier line.

However it's worth to test the following. Could you please replace this part in line 69:
`\""$pbBookID"\"`
with simply:
`$pbBookID`

So the SQL looks like this:
`SELECT BOOKID FROM BOOKS_SETTINGS WHERE BOOKID = $pbBookID;`

Maybe this works for you. Let me know.

**Comment by EastEriq** [comment]
Well, a `head -1` at line 57
```
pbBookID=$(sqlite3 $PBDB "SELECT ID FROM BOOKS_IMPL WHERE TRIM(UPPER(TITLE))=TRIM(UPPER('$currentBookTitle'));" | head -1) 2>> $LOGFILE || currentPlaceInCode="Getting pocketbook book ID" checkError
```
suppresses the error, confirming my assumption of double record, but that is not yet all, apparently... If I then close KR, open a second book, close it, progress percentages are swapped. But that maybe is a quirk of the PB database update and its reflection in the librarian.
If I'll bother to find a repeatable pattern I'll report...

**Comment by EastEriq** [comment]
> `\""$pbBookID"\"`
> with simply:
> `$pbBookID`

This causes no harm, but still, every time I open a new book the librarian updates (with a wrong %) the _previous_ book I have opened in KR. Weird.

**Comment by ckilb** [comment]
I can reproduce this.
Looks like we neither can't rely on the _last_open_ value from the KOReader book table and have to pass the book identifier (probably the title) to the shell script as well - same it's done for the page number now.
I'll change that tomorrow. 

Besides that, if you stop switching books and only test for a single books, does it work for you then?

**Comment by EastEriq** [comment]
Tried another book and got
```
Error detected at No Pocketbook ID found in books_impl. Error is No Pocketbook ID found in books_impl
```
This one at every page turn.
And moreover I have updated KR, and now I'm asked to activate WiFi when I try to close a book. Well, too many issues at once.

**Comment by ckilb** [comment]
the WiFi issue should not be related to this plugin. Did you activate "Automatically keep documents in sync"? Should be disabled.

could you attach the problematic book or send it to christian.kilb@gmail DOT com please?

**Comment by EastEriq** [comment]
Sure. The WiFi issue is likely a Schlimmverbesserung of the latest KR, or it could as well be because of a network demanding plugin which used to be off in the May version and has been defaulted to on in the June one. WiFi control by KR in pocketbook has always been quirky, I'll open a ticket there, later. It was only yet another nuisance in the way, while testing.

I'll see later, maybe tonight, maybe tomorrow, if I can distill repeatable cases of opening certain books in a given order, for the various complaints. I'm afraid that there is more than a single issue, so it will be difficult to isolate.

About `No Pocketbook ID found in books_impl` it may well be that I never opened that book in the pbreader, so there is no associated entry in the pb database. The fact that the dialog pops up at every page turn then it is explained by what the plugin is intended for.

**Comment by ckilb** [comment]
I already did some changes that might fix this for you. If the book can't be found in KOReaders nor Pocketbooks database the plugin/script won't show an error message anymore.

**Comment by EastEriq** [comment]
a quick test: yes, but I still need `LIMIT 1` for the book mentioned above:
```
pbBookID=$(sqlite3 $PBDB "SELECT ID FROM BOOKS_IMPL WHERE TRIM(UPPER(TITLE))=TRIM(UPPER($currentBookTitle)) LIMIT 1;") 2>> $LOGFILE || currentPlaceInCode="Getting pocketbook book ID" checkError
```
now at line 69.

And, I ran in another book with a single quote in the title, which seems to break havoc (`Error: near "educazione": syntax error`). Probably the book title needs to be escaped somehow, but I didn't figure out exactly how. Spaces in the title instead do not seem to pose problem, for the little I tried.

**Comment by EastEriq** [comment]
> And, I ran in another book with a single quote in the title, which seems to break havoc (`Error: near "educazione": syntax error`). Probably the book title needs to be escaped somehow, but I didn't figure out exactly how. Spaces in the title instead do not seem to pose problem, for the little I tried.

fixed by replacing `'$currentBookTitle'` with `\"$currentBookTitle\"` in the couple of relevant places where it appears.

**Comment by EastEriq** [comment]
summing up
```
git diff
diff --git a/pocketbooksync.koplugin/sync.sh b/pocketbooksync.koplugin/sync.sh
index f538cc6..9d744f8 100755
--- a/pocketbooksync.koplugin/sync.sh
+++ b/pocketbooksync.koplugin/sync.sh
@@ -40,8 +40,8 @@ checkError (){
 
 currentBookTitle=$2
 
-koReaderBookID=$(sqlite3 $KRDB "SELECT ID FROM BOOK WHERE TITLE = '$currentBookTitle' ORDER BY LAST_OPEN DESC LIMIT 1;") 2>> $LOGFILE || currentPlaceInCode="Get KoReader book Id" checkError
-echo "SELECT ID FROM BOOK WHERE TITLE = '$currentBookTitle' ORDER BY LAST_OPEN DESC LIMIT 1;" >> $LOGFILE
+koReaderBookID=$(sqlite3 $KRDB "SELECT ID FROM BOOK WHERE TITLE = \"$currentBookTitle\" ORDER BY LAST_OPEN DESC LIMIT 1;") 2>> $LOGFILE || currentPlaceInCode="Get KoReader book Id" checkError
+echo "SELECT ID FROM BOOK WHERE TITLE = \"$currentBookTitle\" ORDER BY LAST_OPEN DESC LIMIT 1;" >> $LOGFILE
 echo "KoReader book id: $koReaderBookID" >> $LOGFILE
 
 if [ -z "$koReaderBookID" ];
@@ -65,7 +65,7 @@ fi
 currentPageNum=$1
 echo "KoReader Current Page Number $currentPageNum" >> $LOGFILE
 
-pbBookID=$(sqlite3 $PBDB "SELECT ID FROM BOOKS_IMPL WHERE TRIM(UPPER(TITLE))=TRIM(UPPER('$currentBookTitle'));") 2>> $LOGFILE || currentPlaceInCode="Getting pocketbook book ID" checkError
+pbBookID=$(sqlite3 $PBDB "SELECT ID FROM BOOKS_IMPL WHERE TRIM(UPPER(TITLE))=TRIM(UPPER(\"$currentBookTitle\")) LIMIT 1;") 2>> $LOGFILE || currentPlaceInCode="Getting pocketbook book ID" checkError
 echo "SELECT ID FROM BOOKS_IMPL WHERE TRIM(UPPER(TITLE))=TRIM(UPPER($currentBookTitle));" >> $LOGFILE
 echo "PocketBook ID: $pbBookID" >> $LOGFILE
```
and yes, the WiFi was because Koreader Sync was mistakenly on.

**Comment by ckilb** [comment]
Thanks! I’ll implement your changes next week.

**Comment by ckilb** [comment]
just pushed a change to get rid of the script and use a single DB query. this should fix the issues. in case you still have issues feel free to create a new issue.
