### ISSUE TITLE
proposing the plugin for pull request to upstream KOReader

### ISSUE THREAD

**Issue by EastEriq** [ckilb/pocketbooksync.koplugin#3]
I think at that at this point it would be a right move, to improve visibility and maintainability. What do you think is still missing for that? One improvement I though of is to disable/remove it completely from the list of plugins displayed, for any device which is not a PocketBook. I imagine that this is probably trivial, but I'm not familiar with the mechanics. From the code of other plugins I presume it should maybe go like
```
local Device = require("device")
if Device:isPocketBook() then
-- ...
end
```

**Comment by EastEriq** [comment]
relevant (closed) KOReader issues: 
- https://github.com/koreader/koreader/issues/1493
- https://github.com/koreader/koreader/issues/6597

**Comment by ckilb** [comment]
thanks for the suggestion. actually i did add that already a few weeks earlier and just forgot to inform here.
